permalink: /:title

gems:
  - jekyll-sitemap

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

safe: true
lsi: false

name: VERSEN
title: VERSEN

production_url: http://www.versen.nl

exclude: ["README.md"]

blogname: VERSEN Blog 
description: VERSEN Blog
url: http://www.versen.nl
